url: http://mcpadvocacia.com
baseurl: 

# Site settings
title: MCP Advogados Associados
email: your-email@domain.com
description: "MCP Advogados Associados"


# Team names, titles and social links
people:
- name: Caroline Luiza Piaz
  pic: 1
  position: Consultora Jurídica
  oab: 
  phone: (47) 98494 - 2710
  email: caroline@mcpadvocacia.com.br
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/caroline-luiza-piaz-386a96161/
    # - title: facebook
    #   url: #
    # - title: stack-overflow
    #   url: #

- name: Maitê De Mendonça Grigull
  pic: 2
  position: Advogada
  oab: 55.7353
  phone: (47) 99116 - 6383
  email: maite@mcpadvocacia.com.br
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    - title: linkedin
      url: https://www.linkedin.com/in/mait%C3%AA-de-mendon%C3%A7a-grigull-033966184/

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: linkedin
    url:
  - title: instagram
    url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty